[[electron lattice]]
    name = "hubbard model"
    crystal = "graphene"
    statespersite = 2
    U = -0.6
    V = 0.0

[[electron lattice]]
    name = "cdw enhanced coupling"
    crystal = "graphene"
    statespersite = 2
    U = -0.6
    V = 0.6
